Repository ga4gh/vrs-python, pull requests merged in 2023-09, with the labels that each got.

#244 Implementing enref/deref for pydantic 2 models
  src/ga4gh/core/_internal/enderef.py
  src/ga4gh/core/_internal/identifiers.py
  src/ga4gh/core/_internal/pydantic.py
  src/ga4gh/vrs/_internal/enderef.py
  src/ga4gh/vrs/_internal/models.py
  tests/test_vrs2.py
Labels: 2.0-alpha

#248 fix: _to_hgvs using wrong vars for hgvs.location.Interval
  src/ga4gh/vrs/extras/translator.py
  tests/extras/cassettes/test_hgvs[NC_000007.14:g.55181220del-expected2].yaml
  tests/extras/cassettes/test_hgvs[NC_000007.14:g.55181230_55181231insGGCT-expected3].yaml
  tests/extras/cassettes/test_hgvs[NC_000007.14:g.55181320A>T-expected1].yaml
  tests/extras/cassettes/test_hgvs[NC_000013.11:g.32316467dup-expected5].yaml
  tests/extras/cassettes/test_hgvs[NC_000013.11:g.32331093_32331094dup-expected4].yaml
  tests/extras/cassettes/test_hgvs[NC_000013.11:g.32936732=-expected0].yaml
  tests/extras/cassettes/test_hgvs[NM_001331029.1:n.872A>G-expected6].yaml
  tests/extras/cassettes/test_hgvs[NM_181798.1:n.1263G>T-expected7].yaml
  tests/extras/test_translator.py
Labels: bug, 2.0-alpha

#247 tests: add tests for tlr._from_gnomad
  tests/extras/cassettes/test_from_gnomad.yaml
  tests/extras/test_translator.py
Labels: 2.0-alpha

#250 Add sqlite3-based object store, with tests
  setup.cfg
  src/ga4gh/vrs/extras/object_store.py
  tests/extras/test_object_store.py
Labels: 2.0-alpha

#252 build: unpin pydantic version
  setup.cfg
  src/ga4gh/vrs/_internal/models.py
Labels: 2.0-alpha, build

#261 feat!: Add CnvTranslator
  src/ga4gh/vrs/extras/translator.py
  src/ga4gh/vrs/extras/vcf_annotation.py
  tests/conftest.py
  tests/extras/cassettes/test_from_hgvs_cx[NC_000013.11:g.26440969_26443305del-CopyChange.EFO_0030069-expected0].yaml
  tests/extras/test_allele_translator.py
  tests/extras/test_cnv_translator.py
  tests/extras/test_variation_normalizer_rest_dp.py
  tests/extras/test_vcf_annotation.py
Labels: enhancement, 2.0-alpha

#264 fix: identify_all method (rm ga4gh prefixes)
  src/ga4gh/core/_internal/identifiers.py
  tests/test_vrs2.py
Labels: bug, 2.0-alpha, priority:high

#265 feat!: update VCFAnnotator + AlleleTranslator
  .github/workflows/python-cqa.yml
  docs/extras/vcf_annotator.md
  setup.cfg
  src/ga4gh/vrs/extras/translator.py
  src/ga4gh/vrs/extras/vcf_annotation.py
  tests/extras/cassettes/test_annotate_vcf.yaml
  tests/extras/cassettes/test_from_beacon.yaml
  tests/extras/cassettes/test_from_gnomad.yaml
  tests/extras/cassettes/test_from_hgvs.yaml
  tests/extras/cassettes/test_from_hgvs_cx[NC_000013.11:g.26440969_26443305del-CopyChange.EFO_0030069-expected0].yaml
  tests/extras/cassettes/test_get_vrs_object_invalid_input.yaml
  tests/extras/cassettes/test_hgvs[NC_000007.14:g.55181220del-expected2].yaml
  tests/extras/cassettes/test_hgvs[NC_000007.14:g.55181230_55181231insGGCT-expected3].yaml
  tests/extras/cassettes/test_hgvs[NC_000007.14:g.55181320A>T-expected1].yaml
  tests/extras/cassettes/test_hgvs[NC_000013.11:g.32316467dup-expected5].yaml
  tests/extras/cassettes/test_hgvs[NC_000013.11:g.32331093_32331094dup-expected4].yaml
  tests/extras/cassettes/test_hgvs[NC_000013.11:g.32936732=-expected0].yaml
  tests/extras/cassettes/test_hgvs[NM_001331029.1:n.872A>G-expected6].yaml
  tests/extras/cassettes/test_hgvs[NM_181798.1:n.1263G>T-expected7].yaml
  tests/extras/cassettes/test_rest_dp_to_hgvs[NC_000007.14:g.55181220del-vo_as_dict2].yaml
  tests/extras/cassettes/test_rest_dp_to_hgvs[NC_000007.14:g.55181230_55181231insGGCT-vo_as_dict3].yaml
  tests/extras/cassettes/test_rest_dp_to_hgvs[NC_000007.14:g.55181320A>T-vo_as_dict1].yaml
  tests/extras/cassettes/test_rest_dp_to_hgvs[NC_000013.11:g.32316467dup-vo_as_dict5].yaml
  tests/extras/cassettes/test_rest_dp_to_hgvs[NC_000013.11:g.32331093_32331094dup-vo_as_dict4].yaml
  tests/extras/cassettes/test_rest_dp_to_hgvs[NC_000013.11:g.32936732=-vo_as_dict0].yaml
  tests/extras/cassettes/test_rest_dp_to_hgvs[NM_001331029.1:n.872A>G-vo_as_dict6].yaml
  tests/extras/cassettes/test_rest_dp_to_hgvs[NM_181798.1:n.1263G>T-vo_as_dict7].yaml
  tests/extras/cassettes/test_to_spdi.yaml
  tests/extras/data/test_vcf_expected_output.vcf.gz
  tests/extras/data/test_vcf_expected_output_no_vrs_attrs.vcf.gz
  tests/extras/test_allele_translator.py
  tests/extras/test_vcf_annotation.py
Labels: enhancement, 2.0-alpha
