Repository ga4gh/vrs-python, pull requests merged in 2023-08, with the labels that each got.

#227 haplotype and genotype handling
  notebooks/testingstuff.ipynb
  src/ga4gh/core/_internal/identifiers.py
  src/ga4gh/core/_internal/pydantic.py
  src/ga4gh/vrs/_internal/models.py
Labels: 2.0-alpha

#228 Adding haplotype and genotype tests
  notebooks/testingstuff.ipynb
  tests/extras/cassettes/test_from_spdi.yaml
  tests/test_vrs2.py
Labels: 2.0-alpha

#233 fix: use camel case for copy change
  src/ga4gh/vrs/_internal/models.py
Labels: 2.0-alpha, priority:high

#234 feat: allele rle normalization + pin pydantic version
  setup.cfg
  src/ga4gh/vrs/normalize.py
  tests/cassettes/test_normalize_allele.yaml
  tests/extras/cassettes/test_hgvs[NC_000007.14:g.55181220del-expected2].yaml
  tests/extras/cassettes/test_hgvs[NC_000007.14:g.55181230_55181231insGGCT-expected3].yaml
  tests/extras/cassettes/test_hgvs[NC_000007.14:g.55181320A>T-expected1].yaml
  tests/extras/cassettes/test_hgvs[NC_000013.11:g.32316467dup-expected5].yaml
  tests/extras/cassettes/test_hgvs[NC_000013.11:g.32331093_32331094dup-expected4].yaml
  tests/extras/cassettes/test_hgvs[NC_000013.11:g.32936732=-expected0].yaml
  tests/extras/cassettes/test_hgvs[NM_001331029.1:n.872A>G-expected6].yaml
  tests/extras/cassettes/test_hgvs[NM_181798.1:n.1263G>T-expected7].yaml
  tests/extras/cassettes/test_to_spdi.yaml
  tests/test_vrs_normalize.py
Labels: enhancement, 2.0-alpha, priority:high

#236 refactor: replace pkg_resources with importlib.metadata
  README.md
  src/ga4gh/core/__init__.py
  src/ga4gh/vrs/__init__.py
  src/ga4gh/vrs/_internal/models.py
Labels: 2.0-alpha, priority:low
