Repository ga4gh/vrs-python, pull requests merged in 2024-07, with the labels that each got.

#419 feat: add make command (`nbready`) to create jupyter notebook venv
  Makefile
  notebooks/getting_started/README.md
Labels: enhancement, priority:low

#420 feat: create enum for gks-common + vrs types
  src/ga4gh/core/_internal/models.py
  src/ga4gh/vrs/_internal/models.py
Labels: enhancement, priority:high

#421 refactor: remove _internal directories
  src/ga4gh/core/__init__.py
  src/ga4gh/core/_internal/__init__.py
  src/ga4gh/core/digests.py
  src/ga4gh/core/domain_models.py
  src/ga4gh/core/enderef.py
  src/ga4gh/core/entity_models.py
  src/ga4gh/core/identifiers.py
  src/ga4gh/core/pydantic.py
  src/ga4gh/vrs/__init__.py
  src/ga4gh/vrs/enderef.py
  src/ga4gh/vrs/models.py
  src/ga4gh/vrs/normalize.py
Labels: priority:high, technical debt

#423 refactor: remove _internal directories
  src/ga4gh/core/__init__.py
  src/ga4gh/core/_internal/__init__.py
  src/ga4gh/core/digests.py
  src/ga4gh/core/enderef.py
  src/ga4gh/core/identifiers.py
  src/ga4gh/core/models.py
  src/ga4gh/core/pydantic.py
  src/ga4gh/vrs/__init__.py
  src/ga4gh/vrs/enderef.py
  src/ga4gh/vrs/models.py
  src/ga4gh/vrs/normalize.py
Labels: priority:high, technical debt

#422 refactor!: split gks-common module into domain + entity
  src/ga4gh/core/__init__.py
  src/ga4gh/core/domain_models.py
  src/ga4gh/core/entity_models.py
  src/ga4gh/vrs/models.py
Labels: priority:medium, technical debt

#426 fix: remove domain models from entity models
  src/ga4gh/core/entity_models.py
Labels: bug, priority:high

#428 fix: f-string in `ga4gh_serialize_as_version`
  src/ga4gh/vrs/models.py
Labels: bug, priority:high

#431 feat: add enum for `as_version` + add restrictions to `ga4gh_serialize_as_version`
  src/ga4gh/core/__init__.py
  src/ga4gh/core/identifiers.py
  src/ga4gh/vrs/models.py
  tests/validation/test_models.py
Labels: enhancement, priority:medium

#430 feat!: update/rename classes to refect public API access and ABC
  src/ga4gh/core/domain_models.py
  src/ga4gh/core/entity_models.py
  src/ga4gh/vrs/models.py
Labels: enhancement, priority:high

#432 refactor: remove unused code + small cleanup
  src/ga4gh/core/__init__.py
  src/ga4gh/core/enderef.py
  src/ga4gh/core/identifiers.py
  src/ga4gh/core/pydantic.py
  src/ga4gh/vrs/models.py
Labels: priority:medium, technical debt

#436 cicd: update actions revs
  .github/workflows/python-cqa.yml
  .github/workflows/release.yml
Labels: priority:low

#435 fix: revert Pydantic custom serializer
  pyproject.toml
  src/ga4gh/core/entity_models.py
  src/ga4gh/core/identifiers.py
  src/ga4gh/vrs/models.py
  tests/validation/test_models.py
Labels: bug, priority:high

#438 docs: fix alt text for github contributors
  README.md
Labels: documentation, priority:low
