Repository ga4gh/vrs-python, pull requests merged in 2025-03, with the labels that each got.

#514 chore: update seqrepo and uta versions to 2024-12-20
  README.md
  docker-compose.yml
  docs/extras/vcf_annotator.md
  docs/setup_help/uta_installation.md
  notebooks/getting_started/1_Quick_Start.ipynb
  notebooks/getting_started/4_Exploring_the_AlleleTranslator.ipynb
  notebooks/getting_started/5_Exploring_the_CnvTranslator.ipynb
  notebooks/getting_started/6_Upcoming_features.ipynb
  tests/cassettes/test_data_proxies[rest_dataproxy].yaml
  tests/cassettes/test_normalize_allele.yaml
  tests/cassettes/test_vcrtest.yaml
  tests/extras/cassettes/test_annotate_vcf_grch37_attrs.yaml
  tests/extras/cassettes/test_annotate_vcf_grch38_attrs.yaml
  tests/extras/cassettes/test_annotate_vcf_grch38_attrs_altsonly.yaml
  tests/extras/cassettes/test_annotate_vcf_grch38_noattrs.yaml
  tests/extras/cassettes/test_annotate_vcf_pickle_only.yaml
  tests/extras/cassettes/test_annotate_vcf_vcf_only.yaml
  tests/extras/cassettes/test_from_beacon.yaml
  tests/extras/cassettes/test_from_gnomad.yaml
  tests/extras/cassettes/test_from_hgvs.yaml
  tests/extras/cassettes/test_get_vrs_object_invalid_input.yaml
  tests/extras/cassettes/test_hgvs[NC_000007.14:g.55181220del-expected2].yaml
  tests/extras/cassettes/test_hgvs[NC_000007.14:g.55181230_55181231insGGCT-expected3].yaml
  tests/extras/cassettes/test_hgvs[NC_000007.14:g.55181320A>T-expected1].yaml
  tests/extras/cassettes/test_hgvs[NC_000013.11:g.32316467dup-expected5].yaml
  tests/extras/cassettes/test_hgvs[NC_000013.11:g.32331093_32331094dup-expected4].yaml
  tests/extras/cassettes/test_hgvs[NC_000013.11:g.32936732=-expected0].yaml
  tests/extras/cassettes/test_hgvs[NC_000019.10:g.289464_289465insCACA-expected8].yaml
  tests/extras/cassettes/test_hgvs[NC_000019.10:g.289485_289500del-expected9].yaml
  tests/extras/cassettes/test_hgvs[NM_001331029.1:c.722A>G-expected6].yaml
  tests/extras/cassettes/test_hgvs[NM_181798.1:c.1007G>T-expected7].yaml
  tests/extras/cassettes/test_rle_seq_limit.yaml
  tests/extras/cassettes/test_to_hgvs_iri_ref_keyerror.yaml
Labels: priority:low, chore

#458 docs: clarify fork procedure for devs
  README.md
Labels: Product Review

#524 docs: add instructions for using podman with vs code dev containers
  notebooks/getting_started/README.md
Labels: documentation, priority:medium
