Repository ga4gh/vrs-python, pull requests merged in 2025-01, with the labels that each got.

#476 build(test): pin vcrpy>=7.0.0 + remove urllib3 from optional dev deps
  pyproject.toml
Labels: priority:low, test, build

#483 style: lint and format with ruff
  .github/workflows/python-cqa.yml
  .pre-commit-config.yaml
  Makefile
  pyproject.toml
  src/ga4gh/core/__init__.py
  src/ga4gh/core/digests.py
  src/ga4gh/core/enderef.py
  src/ga4gh/core/identifiers.py
  src/ga4gh/core/models.py
  src/ga4gh/core/pydantic.py
  src/ga4gh/vrs/__init__.py
  src/ga4gh/vrs/dataproxy.py
  src/ga4gh/vrs/enderef.py
  src/ga4gh/vrs/extras/__init__.py
  src/ga4gh/vrs/extras/decorators.py
  src/ga4gh/vrs/extras/object_store.py
  src/ga4gh/vrs/extras/translator.py
  src/ga4gh/vrs/extras/vcf_annotation.py
  src/ga4gh/vrs/models.py
  src/ga4gh/vrs/normalize.py
  src/ga4gh/vrs/utils/__init__.py
  src/ga4gh/vrs/utils/hgvs_tools.py
  tests/conftest.py
  tests/extras/test_allele_translator.py
  tests/extras/test_cnv_translator.py
  tests/extras/test_dataproxy.py
  tests/extras/test_object_store.py
  tests/extras/test_vcf_annotation.py
  tests/test_vrs.py
  tests/test_vrs_normalize.py
  tests/validation/test_functions.py
  tests/validation/test_models.py
  tests/validation/test_schemas.py
  tests/vcr_support.py
Labels: priority:medium

#486 chore: update gitignore
  .gitignore
Labels: priority:low
