Repository ga4gh/vrs-python, pull requests merged in 2025-02, with the labels that each got.

#491 test: use recommended pytest-vcr settings
  .github/workflows/python-cqa.yml
Labels: priority:low

#494 feat!: break annotator tools into separate submodule
  docs/extras/vcf_annotator.md
  pyproject.toml
  src/ga4gh/vrs/extras/annotator/__init__.py
  src/ga4gh/vrs/extras/annotator/cli.py
  src/ga4gh/vrs/extras/annotator/vcf.py
  tests/extras/test_annotate_vcf.py
Labels: priority:medium

#496 feat!: use pathlib.Paths + streamline related checks
  pyproject.toml
  src/ga4gh/vrs/extras/annotator/cli.py
  src/ga4gh/vrs/extras/annotator/vcf.py
  tests/extras/test_annotate_vcf.py
Labels: priority:medium

#497 feat!: move, reorganize field const variables
  src/ga4gh/vrs/extras/annotator/vcf.py
Labels: priority:low

#499 test: add coverage for dataproxy construction inputs
  src/ga4gh/vrs/dataproxy.py
  tests/cassettes/test_data_proxies[rest_dataproxy].yaml
  tests/extras/test_dataproxy.py
  tests/test_dataproxy.py
Labels: priority:low

#498 feat!: simplify dataproxy construction interface
  docs/extras/vcf_annotator.md
  src/ga4gh/vrs/extras/annotator/cli.py
  src/ga4gh/vrs/extras/annotator/vcf.py
  tests/extras/test_annotate_vcf.py
Labels: priority:medium

#500 refactor: move VCF header update to separate method
  src/ga4gh/vrs/extras/annotator/vcf.py
  tests/extras/test_annotate_vcf.py
Labels: priority:medium

#506 fix: forbid extra attributes when additionalProperties is set to False
  src/ga4gh/core/models.py
  src/ga4gh/vrs/models.py
  tests/validation/test_schemas.py
Labels: bug, priority:high

#508 fix(ci): simplify main branch check
  .github/workflows/release.yml
Labels: priority:high, ci/cd

#509 fix(ci): forgot to remove dependency
  .github/workflows/release.yml
Labels: bug, priority:high, ci/cd

#510 fix(ci): revert #508 and #509 + exclude HEAD from git branch output in pypi release job
  .github/workflows/release.yml
Labels: bug, priority:high, ci/cd

#502 feat!: refactor annotator as ABC, add NDJSON annotation + support optional side effects
  src/ga4gh/vrs/extras/annotator/cli.py
  src/ga4gh/vrs/extras/annotator/vcf.py
  tests/extras/test_annotate_vcf.py
Labels: priority:medium
